---
title: "EDLD 651 Final Project"
author: "Sara Kiros, Ohnmar Khine Min, Chen Su"
format: 
  html:
    highlight-style: espresso
    code-fold: true
execute: 
  eval: true
  echo: true
  warning: false
fig-width: 6.5
fig-height: 8
---


### 0. Loading Packages and Data

```{r}
#| label: load-packages-raw-data

library(tidyverse)
library(here)
library(rio)
library(janitor)
library(ggplot2)
library(dplyr)
library(lubridate)

pwave5 <- import(here("data", "pwave5.xpt")) |>
  characterize() |>
  clean_names() 

```


```{r}
#| label: select-variables

wave5_raw <- pwave5 |>
     select(aid, imonth5, iyear5, h5od1m, h5od1y,
            h5od2a, h5od3, h5od4a, h5od4b, h5od4c,
            h5od4d, h5od4e, h5od4f, h5od4g, h5od8,
            h5lm5, h5lm6, h5lm7, h5lm9, h5ec1, h5ec2,
            h5id9, h5id10a, h5id10b, h5id10c, h5id10d)

```


### 1. Cleaning Employment variables
```{r}
#| label: clean-employment

#Job Type
job_labels <- c(
  "1" = "Military", 
  "2" = "Private for-profit", 
  "3" = "Private nonprofit",
  "4" = "Local government",
  "5" = "State government", 
  "6" = "Federal government", 
  "7" = "Self-employed (non-inc)",
  "8" = "Self-employed (inc)",
  "9" = "Unpaid family worker"
  )


wave5_clean <- wave5_raw |> 
    mutate(
    employed = ifelse(h5lm5 == 1, "Employed",
                      ifelse(h5lm5 %in% c(2, 3), "Not employed", NA)),
    num_jobs = ifelse(h5lm6 %in% 1:4, h5lm6, NA),
    hours_work = ifelse(h5lm7 >= 5 & h5lm7 <= 90, h5lm7, NA),
     job_type = job_labels[as.character(h5lm9)]
)
  
```


### 2. Cleaning Gender Variables

```{r}

wave5_clean <- wave5_clean |> 
  mutate(
    gender = ifelse(h5od2a == 1, "Male", 
                    ifelse(h5od2a == 2, "Female", NA))
  )
```


### 3. Cleaning Insurance status and reasons variables 

```{r}


#Health insurance status (h5id9 & h5id10a,b,c,d)
wave5_clean <- wave5_raw %>%
  mutate(
    h5id9 = factor(
      h5id9,
      levels = c(1, 2, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15),
      labels = c(
        "I get insurance through work",
        "I get insurance through a union",
        "I am covered by my spouse’s or partner’s insurance",
        "I am covered because I am active duty military",
        "I buy private insurance myself",
        "I buy insurance through a Health Insurance Marketplace or Exchange (ACA)",
        "I am on Medicaid",
        "I am on Medicare",
        "I get care through the Department of Veterans Affairs",
        "I am covered through TRI-CARE, CHAMPUS, CHAMP-VA, or other military plan",
        "I am covered through the Indian Health Service",
        "I do not know what my health insurance is",
        "I have no health insurance"
      )
    )
  )

# Factor: Q10 reasons (0 = no, 1 = yes, 97 = legitimate skip)
wave5_clean <- wave5_raw %>%
  mutate(across(
    c(h5id10a, h5id10b, h5id10c, h5id10d),
    ~ factor(.,
             levels = c(0, 1, 97),
             labels = c("no", "yes", "legitimate skip"))
  ))
```


### 4. Cleaning Household income variables 

```{r}

#Household Income in the last calendar year (h5ec2)

wave5_clean <- wave5_raw %>%
  mutate(
    h5ec2 = factor(
      h5ec2,
      levels = 1:13,
      labels = c(
        "Less than $5,000",
        "$5,000 to $9,999",
        "$10,000 to $14,999",
        "$15,000 to $19,999",
        "$20,000 to $24,999",
        "$25,000 to $29,999",
        "$30,000 to $39,999",
        "$40,000 to $49,999",
        "$50,000 to $74,999",
        "$75,000 to $99,999",
        "$100,000 to $149,999",
        "$150,000 to $199,999",
        "$200,000 or more"
      )
    )
  )


```


```{r}

#Renaming Column names 

wave5_clean <- wave5_raw %>%
  rename(
    insurance_status = h5id9,
    reason_a_not_offered_thru_work_or_school = h5id10a,
    reason_b_too_expensive = h5id10b,
    reason_c_no_need_or_want = h5id10c,
    reason_d_denied_insurance = h5id10d,
    household_income = h5ec2
  )

```



**Data Exploratory visualization for Household Income Count**
```{r}
wave5_clean %>%
  filter(!is.na(household_income)) %>%
  group_by(household_income) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = factor(household_income,
                        levels = 1:13,
                        labels = c(
                          "Less than $5,000",
                          "$5,000 to $9,999",
                          "$10,000 to $14,999",
                          "$15,000 to $19,999",
                          "$20,000 to $24,999",
                          "$25,000 to $29,999",
                          "$30,000 to $39,999",
                          "$40,000 to $49,999",
                          "$50,000 to $74,999",
                          "$75,000 to $99,999",
                          "$100,000 to $149,999",
                          "$150,000 to $199,999",
                          "$200,000 or more"
                        )),
                 y = count)) +
  geom_col() +
  labs(title = "Count by Income Level", x = "Household Income Level", y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```


### 5. Cleaning Age variables 

```{r}
#| label: convert-date-variables

survey_date_string <- paste(wave5_clean$iyear5, wave5_clean$imonth5, 1, sep = "-")

wave5_clean <- wave5_clean |>
  mutate(survey_date = ymd(survey_date_string))


birth_date_string <- paste(wave5_clean$h5od1y, wave5_clean$h5od1m, 1, sep = "-")

wave5_clean <- wave5_clean |>
  mutate(birth_date = ymd(birth_date_string))

```


```{r}
#| label: calculate-age-at-survey

wave5_clean <- wave5_clean |>
  mutate(age = interval(birth_date, survey_date) |>
           time_length(unit = "years") |> round(digits = 2))

wave5_clean |>
  ggplot(aes(x=age)) + geom_histogram(binwidth = 1) + 
  labs(title = "Distribution of Participant's Age",
       caption = "Data Source: Wave 5 ADD Health") + 
  theme_minimal()


```



### 6. Cleaning Race & Ethnicity variables

```{r}
#| label: convert-race-ethnicity-variables

wave5_clean <- wave5_clean |>
  mutate(race = case_when(h5od4a == 1 & h5od4b == 0 & h5od4d == 0 & h5od4e == 0 &
                            h5od4f == 0 & h5od4g == 0 ~ "White", 
                          h5od4a == 0 & h5od4b == 1 & h5od4d == 0 & h5od4e == 0 &
                            h5od4f == 0 & h5od4g == 0 ~ "Black", 
                          h5od4a == 0 & h5od4b == 0 & h5od4d == 1 & h5od4e == 0 &
                            h5od4f == 0 & h5od4g == 0 ~ "Asian", 
                          h5od4a == 0 & h5od4b == 0 & h5od4d == 0 & h5od4e == 1 &
                            h5od4f == 0 & h5od4g == 0 ~ "Pacific Islander", 
                          h5od4a == 0 & h5od4b == 0 & h5od4d == 0 & h5od4e == 0 &
                            h5od4f == 1 & h5od4g == 0 ~ "American Indian or Alaska Native",
                          h5od4a == 0 & h5od4b == 0 & h5od4d == 0 & h5od4e == 0 &
                            h5od4f == 0 & h5od4g == 1 ~ "Other Race"))

# NA = multiple race selected, recode to multiracial
wave5_clean <- wave5_clean |>
  mutate(race = replace_na(race, "Multiracial"))


# ethnicity
wave5_clean <- wave5_clean |>
  mutate(ethnicity = case_when(h5od4c == 1 ~ "Hispanic",
                               h5od4c == 0 ~ "Non-Hispanic"))

# NA = Missing for ethnicity
wave5_clean <- wave5_clean |>
  mutate(ethnicity = replace_na(ethnicity, "Missing"))
    
# re-level variables
wave5_clean$race <- factor(wave5_clean$race,levels = c("White",
                                                       "Black",
                                                       "Asian",
                                                       "Pacific Islander",
                                                       "American Indian or Alaska Native",
                                                       "Multiracial",
                                                       "Other Race"))

wave5_clean$ethnicity <- factor(wave5_clean$ethnicity,
                                levels = c("Non-Hispanic",
                                           "Hispanic",
                                           "Missing"))


wave5_clean |>
  ggplot(aes(race)) + geom_bar() + 
  labs(title = "Distribution of Participant's Race and Ethnicity",
       caption = "Data Source: Wave 5 ADD Health") + 
  theme_minimal() + facet_wrap(~ethnicity) + coord_flip()

```

